<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="C:\Users\Mattia\Desktop\spg\server\tests\apis.spec.js">
    <testCase name="tests GET /api/products" duration="325"/>
    <testCase name="tests GET /api/clients" duration="170"/>
    <testCase name="tests GET /api/clients/:id" duration="132"/>
    <testCase name="tests PUT /api/clients/:id/wallet" duration="173"/>
    <testCase name="tests POST /api/addNewUser" duration="677"/>
    <testCase name="tests error POST /api/addNewUser" duration="194"/>
    <testCase name="tests delete /api/sessions/current" duration="169"/>
    <testCase name="tests get /api/sessions/current" duration="173"/>
    <testCase name="tests get /api/nextProducts without performing the login" duration="308"/>
    <testCase name="tests get /api/nextProducts after the login as a customer" duration="161">
      <failure message="Error: expected 200 &quot;OK&quot;, got 500 &quot;Internal Server Error&quot;"><![CDATA[Error: expected 200 "OK", got 500 "Internal Server Error"
    at Object.<anonymous> (C:\Users\Mattia\Desktop\spg\server\tests\apis.spec.js:134:61)
    at Promise.then.completed (C:\Users\Mattia\Desktop\spg\server\node_modules\jest-circus\build\utils.js:390:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\Users\Mattia\Desktop\spg\server\node_modules\jest-circus\build\utils.js:315:10)
    at _callCircusTest (C:\Users\Mattia\Desktop\spg\server\node_modules\jest-circus\build\run.js:218:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _runTest (C:\Users\Mattia\Desktop\spg\server\node_modules\jest-circus\build\run.js:155:3)
    at _runTestsForDescribeBlock (C:\Users\Mattia\Desktop\spg\server\node_modules\jest-circus\build\run.js:66:9)
----
    at Test.Object.<anonymous>.Test._assertStatus (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:304:12)
    at C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:80:15
    at Test.Object.<anonymous>.Test._assertFunction (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:338:11)
    at Test.Object.<anonymous>.Test.assert (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:209:21)
    at Server.localAssert (C:\Users\Mattia\Desktop\spg\server\node_modules\supertest\lib\test.js:167:12)
    at Object.onceWrapper (events.js:482:28)
    at Server.emit (events.js:376:20)
    at emitCloseNT (net.js:1659:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)]]></failure>
    </testCase>
    <testCase name="tests post /api/sesion" duration="273"/>
    <testCase name="tests post /api/sesion error" duration="317"/>
  </file>
</testExecutions>